/**
 * Run modes for the coding agent.
 */

export { InteractiveMode, type InteractiveModeOptions } from "./interactive/interactive-mode.ts";
export { type PrintModeOptions, runPrintMode } from "./print-mode.ts";
export {
	createInProcessRpcClient,
	InProcessRpcClient,
	type InProcessRpcClientEventListener,
	type InProcessRpcClientOptions,
} from "./rpc/in-process-rpc-client.ts";
export {
	createIrohRemoteAgentRuntime,
	createIrohRemoteAgentRuntimeWithSessionSelection,
	type IrohRemoteAgentRuntimeOptions,
	type IrohRemoteAgentRuntimeResult,
	type IrohRemoteAgentRuntimeSessionSelection,
	type IrohRemoteSubagentRuntimeCreatedEvent,
} from "./rpc/iroh-remote-agent-runtime.ts";
export {
	type IrohRemoteCompletedCommand,
	type IrohRemoteCompletionState,
	type IrohRemoteNotificationKind,
	type IrohRemoteNotificationRequest,
	type IrohRemoteRpcModeOptions,
	runIrohRemoteRpcMode,
} from "./rpc/iroh-remote-rpc-mode.ts";
export {
	type ModelInfo,
	RpcClient,
	type RpcClientEvent,
	type RpcClientOptions,
	type RpcEventListener,
	type RpcExtensionErrorEvent,
	type RpcSubagentDisposedEvent,
	type RpcSubagentEndEvent,
	type RpcSubagentEvent,
} from "./rpc/rpc-client.ts";
export { type RpcModeOptions, type RpcSessionChange, runRpcMode } from "./rpc/rpc-mode.ts";
export { RpcTransportClient, type RpcTransportClientOptions } from "./rpc/rpc-transport-client.ts";
export type {
	RpcActiveCompaction,
	RpcActiveToolExecution,
	RpcBackgroundJobSnapshot,
	RpcBackgroundJobSummary,
	RpcBackgroundJobsChangedEvent,
	RpcCancelJobResponse,
	RpcClientCapabilityFeature,
	RpcCommand,
	RpcExtensionUIRequest,
	RpcExtensionUIResponse,
	RpcGitContext,
	RpcGitContextChangedEvent,
	RpcHostActionRequest,
	RpcHostActionResponse,
	RpcHostActionUpdate,
	RpcListJobsResponse,
	RpcListSubagentsResponse,
	RpcMcpCapabilitiesResponse,
	RpcMcpPromptContentResponse,
	RpcMcpPromptsResponse,
	RpcMcpRecentCallsResponse,
	RpcMcpResourceContentResponse,
	RpcMcpResourcesResponse,
	RpcMcpServerResponse,
	RpcMcpServersResponse,
	RpcMcpToolResponse,
	RpcMcpToolsResponse,
	RpcPendingHostActionsResponse,
	RpcPushPlatform,
	RpcPushProvider,
	RpcReadJobResponse,
	RpcRegisterPushTargetArgs,
	RpcRegisterPushTargetResponse,
	RpcResponse,
	RpcReviewAcknowledgmentResponse,
	RpcReviewWorkflowDescriptor,
	RpcReviewWorkflowLifecycleStatus,
	RpcReviewWorkflowListResponse,
	RpcReviewWorkflowResultResponse,
	RpcSessionListItem,
	RpcSessionState,
	RpcSubagentDefinition,
	RpcSubagentDefinitionSource,
	RpcSubagentSourceInfo,
	RpcSubagentStartResponse,
	RpcSubscriptionUsageReport,
	RpcTranscriptItem,
	RpcTranscriptResponse,
	RpcTranscriptToolStatus,
	RpcWorkflowEvent,
	RpcWorkflowKind,
	RpcWorkflowStatus,
	RpcWorkflowToolEvent,
	UiActionArgumentDescriptor,
	UiActionArgumentType,
	UiActionCapabilities,
	UiActionCapabilityFeature,
	UiActionCategory,
	UiActionDescriptor,
	UiActionInvocationQueueBehavior,
	UiActionInvocationResponse,
	UiActionInvocationStatus,
	UiActionListResponse,
	UiActionListScope,
	UiActionOptionDescriptor,
	UiActionPresentationHint,
	UiActionPresentationKind,
	UiActionScalar,
	UiActionSlashAlias,
	UiActionSource,
	UiActionStateDescriptor,
	UiActionStateType,
	UiActionStreamingBehavior,
} from "./rpc/rpc-types.ts";
