package appattest

import (
	"crypto/ecdsa"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"

	"github.com/fxamacker/cbor/v2"
)

// These independently published device signatures cannot be regenerated by
// changing our fixture signer to mirror a mistake in the production verifier.
// Provenance and MIT attribution are recorded alongside the test data.
func TestIndependentPublishedIOSAssertions(t *testing.T) {
	data, err := os.ReadFile("testdata/independent-ios-assertions.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixtures []struct {
		Name, AppID, PublicKey, ClientData, Assertion string
		Counter                                       uint32
	}
	if err := json.Unmarshal(data, &fixtures); err != nil || len(fixtures) != 4 {
		t.Fatalf("fixture decoding: %v", err)
	}
	decode := func(value string) []byte {
		t.Helper()
		data, err := base64.StdEncoding.DecodeString(value)
		if err != nil {
			t.Fatal(err)
		}
		return data
	}
	for _, f := range fixtures {
		t.Run(f.Name, func(t *testing.T) {
			v, err := NewAppleVerifier(f.AppID, "production", 2, nil)
			if err != nil {
				t.Fatal(err)
			}
			hash := sha256.Sum256(decode(f.ClientData))
			key, assertion := decode(f.PublicKey), decode(f.Assertion)
			counter, err := v.VerifyAssertion(key, assertion, hash, "fixture-build-not-attested")
			if err != nil || counter != f.Counter {
				t.Fatalf("counter=%d reason=%s error=%v", counter, RejectionReason(err), err)
			}
			hash[0]++
			if _, err := v.VerifyAssertion(key, assertion, hash, "fixture-build-not-attested"); RejectionReason(err) != "assertion_signature" {
				t.Fatal("accepted modified request or rejected before signature check")
			}
		})
	}
}

func TestAssertionRejectsSignatureOverUnhashedNonce(t *testing.T) {
	f := makeAttestationFixtureWithExtensions(t, nil)
	public, err := f.verifier.VerifyAttestation(f.keyID, f.object, f.hash, "4")
	if err != nil {
		t.Fatal(err)
	}
	var a assertionObject
	if err := cbor.Unmarshal(f.assertionWithExtensions(t, 1, f.hash, nil), &a); err != nil {
		t.Fatal(err)
	}
	nonce := sha256.Sum256(append(append([]byte(nil), a.AuthData...), f.hash[:]...))
	a.Signature, err = ecdsa.SignASN1(rand.Reader, f.key, nonce[:])
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := cbor.Marshal(a)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.verifier.VerifyAssertion(public, encoded, f.hash, "4"); RejectionReason(err) != "assertion_signature" {
		t.Fatal("accepted the incorrect single-hash signature")
	}
}
