// Core session management

export type {
	JsonCompatible,
	JsonCompatibleInput,
	JsonObject,
	JsonPrimitive,
	JsonValue,
} from "@hansjm10/volt-ai";
export { type Args, parseArgs } from "./cli/args.ts";
// Protocol clients: in-process loopback, a `volt --mode rpc` child, or any transport
export {
	createLoopbackClient,
	LoopbackClient,
	type LoopbackClientOptions,
	ProtocolClient,
	type ProtocolClientOptions,
	type ProtocolIntentOptions,
	type ProtocolPromptOptions,
	ProtocolQueryError,
	ProtocolRejectedError,
	RpcProcessClient,
	type SpawnRpcClientOptions,
	spawnRpcClient,
} from "./client/protocol-client.ts";
// Config paths
export { getAgentDir, getDocsPath, getExamplesPath, getPackageDir, getReadmePath, VERSION } from "./config.ts";
export {
	type ActiveCompaction,
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type AgentSessionState,
	type CompactionReason,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateMessagesTokens,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { ConversationLockedError, type ConversationLockHolder } from "./core/conversation-log/conversation-lock.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionDefinition,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionManifest,
	ExtensionOperationEvent,
	ExtensionOperationOrigin,
	ExtensionRuntime,
	ExtensionServiceName,
	ExtensionServicesCause,
	ExtensionServicesContext,
	ExtensionServicesContribution,
	ExtensionServicesEvidence,
	ExtensionServicesFailure,
	ExtensionServicesFailureStatus,
	ExtensionServicesFindResult,
	ExtensionServicesInput,
	ExtensionServicesLimits,
	ExtensionServicesLocation,
	ExtensionServicesLocationsResult,
	ExtensionServicesReadResult,
	ExtensionServicesRepository,
	ExtensionServicesSearchResult,
	ExtensionServicesSkill,
	ExtensionServicesSnapshot,
	ExtensionServicesStatus,
	ExtensionServicesSymbol,
	ExtensionServicesSymbolsResult,
	ExtensionServicesTaskAdmission,
	ExtensionServicesTaskContext,
	ExtensionServicesTaskHandle,
	ExtensionServicesTaskSpec,
	ExtensionServicesTaskState,
	ExtensionServicesTaskSummary,
	ExtensionSettingsOf,
	ExtensionSettingsShape,
	ExtensionSettingValue,
	ExtensionShortcut,
	ExtensionSource,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	PolicyRegistration,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	RequestBoundaryEvent,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionIntentResult,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SettingsChangedEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	StartWorkOptions,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WebFetchToolCallEvent,
	WebFetchToolResultEvent,
	WebSearchToolCallEvent,
	WebSearchToolResultEvent,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WorkKindDeclaration,
	WorkRun,
	WorkRunContext,
	WorkRunResult,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineManifest,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionPermissionError,
	ExtensionRunner,
	ExtensionSettingsError,
	ExtensionUIDismissedError,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWebFetchToolResult,
	isWebSearchToolResult,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (Git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export {
	detectGitOperation,
	type GitContextObservation,
	type GitContextObservationListener,
	GitContextProvider,
	type GitContextProviderOptions,
	type GitContextSubscriptionOptions,
	type ParsedGitStatus,
	parseGitStatusPorcelainV2,
} from "./core/git-context-provider.ts";
export {
	type GitContextProviderLease,
	GitContextProviderPool,
	type GitContextProviderPoolAcquireOptions,
} from "./core/git-context-provider-pool.ts";
export {
	type HostAnswerResult,
	type HostRequestCancelReason,
	type HostRequestOptions,
	type HostRequestOutcome,
	type LiveClient,
	LiveState,
	type LiveUpdate,
	type PendingHostRequest,
} from "./core/host/live-state.ts";
// LSP
export {
	installHintForCommand,
	installRecipeForCommand,
	LspClient,
	type LspClientOptions,
	type LspDiagnostic,
	type LspDiagnosticResult,
	type LspDiagnosticSource,
	type LspFreshness,
	type LspInstallCommandOptions,
	type LspInstallCommandResult,
	type LspInstallRecipe,
	type LspInstallRunner,
	type LspLaunchDescriptor,
	type LspLaunchSource,
	LspManager,
	type LspManagerOptions,
	type LspOperationMetadata,
	type LspOutcome,
	type LspProjectContext,
	type LspResult,
	type LspServerLease,
	LspServerPool,
	type LspServerPoolAcquireOptions,
	type LspServerSettings,
	type LspServerStatus,
	type LspSettings,
	type LspSeverity,
	type LspTraceDirection,
	LspTracer,
	languageIdForExtension,
	lspResult,
	lspSucceeded,
	type ResolvedLspConfig,
	type ResolvedLspServerConfig,
	type ResolveLspLaunchOptions,
	resolveLspConfig,
	resolveLspLaunch,
	runDefaultLspInstallCommand,
} from "./core/lsp/index.ts";
export {
	createMcpDirectToolDefinitions,
	DEFAULT_MCP_SETTINGS,
	DefaultMcpClientFactory,
	finalizeMcpConfig,
	getMcpRpcCapabilities,
	hasProjectMcpConfig,
	listMcpRpcServers,
	loadMcpConfig,
	McpAuditLogger,
	type McpAuthConfig,
	type McpClientFactory,
	type McpConfigDiagnostic,
	type McpDirectToolCandidate,
	type McpDirectToolDetails,
	type McpGatewayCallResult,
	type McpGatewayInput,
	type McpGatewayToolDetails,
	type McpGatewayToolInput,
	type McpGatewayToolOptions,
	McpManager,
	McpMetadataCache,
	type McpOAuthBrowserCompleteResult,
	type McpOAuthBrowserStartResult,
	type McpOAuthDevicePollResult,
	type McpOAuthDeviceStartResult,
	McpOAuthStore,
	type McpOAuthStoredRecord,
	McpOutputStore,
	type McpResolvedConfig,
	type McpResolvedServerConfig,
	type McpRpcCapabilities,
	type McpServerSummary,
	type McpSettings,
	type McpToolSummary,
	searchMcpMetadata,
} from "./core/mcp/index.ts";
export { type CustomMessage, type CustomMessageInput, convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageInstallOptions,
	PackageInstallScriptPolicy,
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { Personality } from "./core/personality.ts";
export type { PromptCacheStatus } from "./core/prompt-cache-status.ts";
export {
	emptyLiveFold,
	foldLiveCommit,
	foldLiveFrame,
	foldLiveItems,
	type LiveFoldState,
	type LiveStreamingAssistant,
	type LiveStreamingTool,
	liveCommitOf,
} from "./core/protocol/live-fold.ts";
export { localProfile, type Profile, type ProfileLimits } from "./core/protocol/profiles.ts";
export {
	type ProtocolConnection,
	type ProtocolPeer,
	type ServeConnectionOptions,
	serveConnection,
} from "./core/protocol/server/connection.ts";
export {
	attachJsonlLineReader,
	createIrohRpcTransport,
	createJsonlRpcTransport,
	createJsonlStreamRpcTransport,
	createLoopbackRpcTransportPair,
	DEFAULT_IROH_READ_LIMIT,
	DEFAULT_IROH_RPC_MAX_ENCODED_LINE_BYTES,
	DEFAULT_IROH_RPC_MAX_LINE_BYTES,
	type IrohBiStreamLike,
	type IrohBytes,
	type IrohRecvStreamLike,
	type IrohRpcTransportOptions,
	type IrohSendStreamLike,
	type JsonlRpcTransportOptions,
	type JsonlStreamRpcTransportOptions,
	type LoopbackRpcTransportPair,
	type RpcCloseHandler,
	type RpcLineHandler,
	type RpcTransport,
	serializeJsonLine,
} from "./core/protocol/transport/index.ts";
export {
	type AuthorizeIrohRemoteClientOptions,
	assertIrohRemoteHandshakeHostIdentity,
	assertIrohRemoteTicketNotExpired,
	assertIrohRemoteTicketPayloadHostIdentity,
	attachCompletionNotifications,
	authorizeIrohRemoteClient,
	type CompletionNotifications,
	type CompletionNotificationsOptions,
	type CreateIrohRemoteHostMetadataOptions,
	cloneIrohRemoteRpcGrant,
	createEmptyIrohRemoteHostState,
	createIrohRemoteExplicitAccess,
	createIrohRemoteHandshakeFailure,
	createIrohRemoteHandshakeSuccess,
	createIrohRemoteHostMetadata,
	createIrohRemotePresetAccess,
	createIrohRemoteProjectionSanitizer,
	createIrohRemoteRpcGrant,
	createIrohRemoteSanitizedReconnectTicket,
	createIrohRemoteSanitizedReconnectTicketPayload,
	createIrohRemoteTicketQrCode,
	DEFAULT_IROH_REMOTE_ALLOW_TOOLS,
	DEFAULT_IROH_REMOTE_CONTROL_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_DEVICE_LOG_MAX_CONTENT_BYTES,
	DEFAULT_IROH_REMOTE_HANDSHAKE_MAX_LINE_BYTES,
	DEFAULT_IROH_REMOTE_HANDSHAKE_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_PAIRING_SECRET_TOMBSTONE_RETENTION_MS,
	DEFAULT_IROH_REMOTE_PAIRING_TICKET_TTL_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_RETRY_ATTEMPTS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_RETRY_DELAY_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_URL,
	decodeIrohRemoteTicketPayload,
	encodeIrohRemoteTicketPayload,
	ensureIrohRemoteControlDirectory,
	findIrohRemoteClient,
	findIrohRemoteRevokedClient,
	formatIrohRemoteHostFingerprint,
	formatIrohRemoteTicketQrCode,
	formatIrohRemoteTicketQrCodeTerminal,
	getAvailableIrohRemoteWorkspaceNames,
	getIrohRemoteAccessPreset,
	getIrohRemoteControlPath,
	getIrohRemotePairingVerificationDetails,
	getIrohRemoteStreamCapability,
	getIrohRemoteUnsafeAllowedTools,
	getIrohRemoteWorkspaceAvailabilityStatus,
	getIrohRemoteWorkspaceStatuses,
	hashIrohRemotePairingSecret,
	hashIrohRemotePushToken,
	hasIrohRemoteRpcCapability,
	IROH_REMOTE_ACCESS_PRESET_NAMES,
	IROH_REMOTE_ACCESS_PRESETS,
	IROH_REMOTE_ALPN,
	IROH_REMOTE_CONVERSATION_STREAMS_FEATURE,
	IROH_REMOTE_DEVICE_LOGS_DIR_SEGMENTS,
	IROH_REMOTE_HANDSHAKE_TYPE,
	IROH_REMOTE_HELLO_TYPE,
	IROH_REMOTE_HOST_FEATURES,
	IROH_REMOTE_HOST_HANDSHAKE_FAILURE_OUTCOMES,
	IROH_REMOTE_MULTI_STREAMS_FEATURE,
	IROH_REMOTE_OUTCOMES,
	IROH_REMOTE_PAIR_CONTROL_REQUEST_TYPE,
	IROH_REMOTE_PAIR_CONTROL_RESPONSE_TYPE,
	IROH_REMOTE_REDACTED_BASH_OUTPUT_PATH,
	IROH_REMOTE_REDACTED_EXPORT_PATH,
	IROH_REMOTE_REDACTED_SESSION_FILE,
	IROH_REMOTE_REVOKE_CONTROL_REQUEST_TYPE,
	IROH_REMOTE_REVOKE_CONTROL_RESPONSE_TYPE,
	IROH_REMOTE_RPC_CAPABILITIES,
	IROH_REMOTE_RPC_GRANT_SCHEMA_VERSION,
	IROH_REMOTE_SESSION_ID_PATTERN,
	IROH_REMOTE_SESSION_RUNTIME_STATE_FEATURE,
	IROH_REMOTE_TICKET_PREFIX,
	IROH_REMOTE_UNSAFE_TOOL_NAMES,
	IROH_REMOTE_WORKSPACE_HAS_WORKTREES_ERROR,
	IROH_REMOTE_WORKSPACE_UNAVAILABLE_RETRY_AFTER_MS,
	IROH_REMOTE_WORKTREE_ID_PATTERN,
	IROH_REMOTE_WORKTREES_FEATURE,
	type IrohRemoteAccessPreset,
	type IrohRemoteAccessPresetName,
	type IrohRemoteActiveStreamEntry,
	IrohRemoteActiveStreamRegistry,
	type IrohRemoteAuditEvent,
	type IrohRemoteAuditEventInput,
	IrohRemoteAuditLogger,
	type IrohRemoteAuditLoggerOptions,
	type IrohRemoteAuditSink,
	type IrohRemoteClient,
	type IrohRemoteClientAccessUpdateResult,
	type IrohRemoteClientAuthorizationFailure,
	type IrohRemoteClientAuthorizationResult,
	type IrohRemoteClientAuthorizationSuccess,
	IrohRemoteClientEngine,
	type IrohRemoteClientEngineOptions,
	type IrohRemoteClientHandshakeResponseResult,
	type IrohRemoteClientReadHandshakeResponseOptions,
	type IrohRemoteClientRePairApprovalResult,
	type IrohRemoteClientRevocationResult,
	type IrohRemoteClientTicketHello,
	type IrohRemoteCompletionState,
	type IrohRemoteConnectionOptions,
	type IrohRemoteControlClientOptions,
	type IrohRemoteControlRequest,
	type IrohRemoteControlServerListenOptions,
	type IrohRemoteConversationHandshakeMetadata,
	type IrohRemoteConversationSelection,
	type IrohRemoteConversationTarget,
	type IrohRemoteDeviceLogUpload,
	type IrohRemoteDeviceLogUploadOptions,
	type IrohRemoteGrantedClient,
	type IrohRemoteGrantedPendingPairingTicket,
	type IrohRemoteGrantedRevokedClient,
	IrohRemoteHandshakeError,
	type IrohRemoteHandshakeFailure,
	type IrohRemoteHandshakeLineReadOptions,
	type IrohRemoteHandshakeLineReadResult,
	type IrohRemoteHandshakeResponse,
	type IrohRemoteHandshakeSuccess,
	type IrohRemoteHello,
	type IrohRemoteHelloMode,
	IrohRemoteHostEngine,
	type IrohRemoteHostEngineOptions,
	type IrohRemoteHostFeature,
	type IrohRemoteHostHandshakeFailureOutcome,
	type IrohRemoteHostHandshakeMetadata,
	type IrohRemoteHostHandshakeResult,
	type IrohRemoteHostMetadata,
	type IrohRemoteHostPairOptions,
	type IrohRemoteHostReadHandshakeOptions,
	type IrohRemoteHostState,
	IrohRemoteHostStateManager,
	type IrohRemoteHostStateManagerOptions,
	IrohRemoteInMemoryPushNotificationDeduper,
	type IrohRemoteNotificationKind,
	type IrohRemoteOutcome,
	IrohRemoteOutcomeError,
	type IrohRemotePairControlClientOptions,
	type IrohRemotePairControlRequest,
	type IrohRemotePairControlResponse,
	type IrohRemotePairingSecretTombstone,
	type IrohRemotePairingSecretTombstoneOutcome,
	type IrohRemotePairingTicket,
	type IrohRemotePairingVerificationDetails,
	type IrohRemotePendingPairingTicket,
	type IrohRemoteProjectionSanitizer,
	type IrohRemotePushNotificationDeduper,
	type IrohRemotePushNotificationDelivery,
	type IrohRemotePushNotificationDeliveryStatus,
	IrohRemotePushNotificationDispatcher,
	type IrohRemotePushNotificationDispatcherOptions,
	type IrohRemotePushNotificationIntent,
	type IrohRemotePushRelayClient,
	IrohRemotePushRelayHttpClient,
	type IrohRemotePushRelayHttpClientOptions,
	IrohRemotePushRelayHttpError,
	type IrohRemotePushRelayNotificationRequest,
	type IrohRemotePushRelayNotificationResult,
	type IrohRemotePushTarget,
	type IrohRemotePushTargetPlatform,
	type IrohRemotePushTargetProvider,
	type IrohRemotePushTargetRegistrationRequest,
	type IrohRemotePushTargetRegistrationResult,
	type IrohRemoteRelayMode,
	type IrohRemoteRevokeControlClientOptions,
	type IrohRemoteRevokeControlRequest,
	type IrohRemoteRevokeControlResponse,
	type IrohRemoteRevokedClient,
	type IrohRemoteRpcCapability,
	type IrohRemoteRpcGrant,
	type IrohRemoteRuntimeToolPolicy,
	type IrohRemoteSanitizedReconnectTicketPayload,
	type IrohRemoteSanitizerOptions,
	type IrohRemoteTicketPayload,
	type IrohRemoteTicketQrCode,
	type IrohRemoteTicketQrCodeFormatOptions,
	type IrohRemoteUnsafeApproval,
	type IrohRemoteWorkspace,
	type IrohRemoteWorkspaceAvailabilityClassifier,
	type IrohRemoteWorkspaceAvailabilityStatus,
	type IrohRemoteWorkspaceDiscoveryTarget,
	IrohRemoteWorkspaceHasWorktreesError,
	type IrohRemoteWorkspaceManagementTarget,
	type IrohRemoteWorkspaceMetadataSnapshot,
	type IrohRemoteWorkspaceStatus,
	type IrohRemoteWorkspaceTrustStore,
	type IrohRemoteWorkspaceWorktree,
	type IrohRemoteWorktreeRpcBackend,
	type IrohRemoteWorktreeSummary,
	isIrohRemoteAccessPresetName,
	isIrohRemoteClientAllowedForWorkspace,
	isIrohRemoteHostHandshakeFailureOutcome,
	isIrohRemoteOutcome,
	isIrohRemoteRelayMode,
	isIrohRemoteRuntimeToolPolicyWithin,
	isIrohRemoteSessionId,
	isIrohRemoteWorkspaceHasWorktreesError,
	isIrohRemoteWorkspaceName,
	isIrohRemoteWorktreeId,
	listenIrohRemoteControlServer,
	normalizeIrohRemoteAllowTools,
	parseIrohRemoteAllowTools,
	parseIrohRemoteClient,
	parseIrohRemoteControlRequest,
	parseIrohRemoteHandshakeResponse,
	parseIrohRemoteHandshakeResponseLine,
	parseIrohRemoteHello,
	parseIrohRemoteHelloLine,
	parseIrohRemoteHostState,
	parseIrohRemotePairControlRequest,
	parseIrohRemotePairControlResponse,
	parseIrohRemotePairingSecretTombstone,
	parseIrohRemotePendingPairingTicket,
	parseIrohRemotePushTarget,
	parseIrohRemoteRevokeControlRequest,
	parseIrohRemoteRevokeControlResponse,
	parseIrohRemoteRevokedClient,
	parseIrohRemoteRpcCapabilities,
	parseIrohRemoteRpcGrant,
	parseIrohRemoteTicketPayload,
	parseIrohRemoteWorkspace,
	parseIrohRemoteWorkspaceSpec,
	parseIrohRemoteWorkspaceWorktree,
	parseRegisterPushTargetArgs,
	type ResolveIrohRemoteRuntimeToolPolicyOptions,
	type ResolveIrohRemoteWorkspaceProjectTrustOptions,
	readIrohRemoteHandshakeLine,
	readIrohRemoteHostState,
	requestIrohRemoteActiveRevocation,
	requestIrohRemotePairingTicket,
	resolveIrohRemoteRuntimeToolPolicy,
	resolveIrohRemoteWorkspaceProjectTrusted,
	selectIrohRemoteWorkspace,
	serveIrohRemoteConnection,
	shouldReplaceIrohRemoteIntegratedRuntimeForAuthorization,
	uploadIrohRemoteDeviceLog,
	upsertIrohRemoteWorkspace,
	usesDefaultIrohRemoteAllowTools,
	writeIrohRemoteHandshakeResponse,
	writeIrohRemoteHello,
	writeIrohRemoteHostState,
} from "./core/remote/iroh/index.ts";
export type {
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
	ResourceLoaderSubagentsResult,
} from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	type AgentSessionDiagnostic,
	type AgentSessionServices,
	ClientScope,
	type ConversationFactory,
	type ConversationFactoryResult,
	ConversationHost,
	type ConversationHostOptions,
	type ConversationLifetime,
	type ConversationTarget,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createInspectionTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createSubagentRegistryTool,
	createSubagentTool,
	createWebFetchTool,
	createWebSearchTool,
	createWriteTool,
	executePlan,
	type ForkIntentResult,
	type HostClient,
	type HostClientMove,
	HostedConversation,
	type HostedRedirect,
	type NewSessionIntentOptions,
	type OpenConversationOptions,
	type OpenConversationResult,
	type OpenForResult,
	openFork,
	openImport,
	openNewSession,
	openStoredSession,
	openStoredSessionById,
	PinnedConversationError,
	type PromptTemplate,
	type RedirectTarget,
	SessionImportFileNotFoundError,
	type SubagentRuntimeContext,
	type SwitchSessionIntentOptions,
	type WhenUnattached,
	type WorkspaceSessionSummary,
} from "./core/sdk.ts";
export { QueueClearPersistenceError } from "./core/session/client-inputs.ts";
export type { ExtensionClient, ExtensionTerminalUI } from "./core/session/extension-binding.ts";
export type { HostActionOutcome, HostActionRequest, HostActions } from "./core/session/host-actions.ts";
export {
	assertCurrentSessionSnapshot,
	type BranchSummaryEntry,
	type CompactionEntry,
	CURRENT_SESSION_SNAPSHOT_VERSION,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	createSessionSnapshotHeader,
	type FastModeChangeEntry,
	type FileEntry,
	getDefaultSessionDir,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	type SessionListOptions,
	SessionManager,
	type SessionMessageEntry,
	type SessionReference,
	type SessionSnapshotHeader,
	serializeSessionJsonlSnapshot,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export type { LogWriter, SessionWriter } from "./core/session-writer.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type ImageSettings,
	type PackageSource,
	type ProfileSettings,
	type ProfileStorageSettings,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export {
	createBuiltInSubagentDefinitions,
	DEFAULT_SUBAGENT_DELEGATION_LIMITS,
	DEFAULT_SUBAGENT_TURN_LIMITS,
	type DiscoverSubagentDefinitionsOptions,
	discoverSubagentDefinitions,
	type FileSubagentDefinitionSource,
	type ParseSubagentDefinitionOptions,
	type ParseSubagentDefinitionResult,
	parseSubagentDefinition,
	type SubagentActivity,
	type SubagentActivityEvent,
	type SubagentActivityListener,
	type SubagentCallerDepthCapacitySnapshot,
	type SubagentCapacityLimitSnapshot,
	type SubagentDefinition,
	SubagentDefinitionConfigurationError,
	SubagentDefinitionNotFoundError,
	type SubagentDefinitionSource,
	SubagentDelegationScope,
	type SubagentDelegationScopeLease,
	type SubagentDelegationScopeLimits,
	type SubagentDelegationScopeOptions,
	type SubagentDelegationScopeSnapshot,
	type SubagentDiscoveryResult,
	type SubagentEndEvent,
	type SubagentEvent,
	type SubagentEventListener,
	type SubagentHandle,
	SubagentManager,
	type SubagentManagerOptions,
	type SubagentResult,
	type SubagentResultStatus,
	type SubagentRunStatus,
	type SubagentRuntimeCreatedEvent,
	type SubagentRuntimeRegistration,
	type SubagentSpawnAdmissionResult,
	type SubagentSpawnBatchLease,
	type SubagentSpawnCapacityConstraint,
	type SubagentSpawnCapacityMode,
	type SubagentSpawnCapacityPhase,
	type SubagentSpawnCapacityProposal,
	type SubagentSpawnCapacitySnapshot,
	type SubagentSpawnPreflight,
	type SubagentStartByNameOptions,
	type SubagentStartOptions,
	type SubagentTreeCapacitySnapshot,
	type SubagentTurnBudgetEvent,
	type SubagentTurnLimits,
	type SubagentWorkBinding,
} from "./core/subagents/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./core/theme/runtime.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	cleanProviderContent,
	createBashToolDefinition,
	createDefaultWebFetchOperations,
	createDefaultWebSearchOperations,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createImageGenTool,
	createImageGenToolDefinition,
	createLocalBashOperations,
	createLspToolDefinition,
	createLsToolDefinition,
	createMcpTool,
	createMcpToolDefinition,
	createReadToolDefinition,
	createSubagentRegistryToolDefinition,
	createSubagentToolDefinition,
	createWebFetchToolDefinition,
	createWebSearchToolDefinition,
	createWriteToolDefinition,
	DEFAULT_ACTIVE_TOOL_NAMES,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	DEFAULT_SUBAGENT_AGGREGATE_OUTPUT_MAX_BYTES,
	DEFAULT_SUBAGENT_OUTPUT_MAX_BYTES,
	type DefaultWebFetchOperationsOptions,
	type DefaultWebSearchOperationsOptions,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type ExtractedHtml,
	extractHtml,
	extractUrls,
	FALLBACK_MAX_LINES,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	htmlToText,
	type ImageGenFetcher,
	type ImageGenModelContext,
	type ImageGenModelContextProvider,
	type ImageGenRecentImagesProvider,
	type ImageGenReferenceFileHandle,
	type ImageGenReferenceFileOperations,
	type ImageGenToolDetails,
	type ImageGenToolInput,
	type ImageGenToolOptions,
	isCodexImageGenerationModel,
	type LsOperations,
	type LspAction,
	type LspNavigationProvider,
	type LspToolDetails,
	type LspToolInput,
	type LspToolOptions,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	MAX_SNIPPET_CHARS,
	normalizeFetchUrl,
	parseProviderContent,
	READ_ONLY_TOOL_NAMES,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	SUBAGENT_REGISTRY_TOOL_NAME,
	type SubagentRegistryToolInput,
	type SubagentRegistryToolOptions,
	type SubagentToolDetails,
	type SubagentToolInput,
	type SubagentToolManager,
	type SubagentToolOptions,
	type SubagentToolUsageDetails,
	type ToolDiagnosticsProvider,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WebFetchDownloadTruncation,
	type WebFetchFetcher,
	type WebFetchHostResolver,
	type WebFetchOperations,
	type WebFetchRequest,
	type WebFetchResponse,
	type WebFetchToolDetails,
	type WebFetchToolInput,
	type WebFetchToolOptions,
	type WebFetchUrlPolicy,
	type WebFetchUrlSource,
	type WebSearchFetcher,
	type WebSearchModelContext,
	type WebSearchModelContextProvider,
	type WebSearchOperations,
	type WebSearchRequest,
	type WebSearchResponse,
	type WebSearchResult,
	type WebSearchToolDetails,
	type WebSearchToolInput,
	type WebSearchToolOptions,
	type WriteOperations,
	type WriteToolDetails,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	createIrohRemoteAgentRuntime,
	createIrohRemoteAgentRuntimeWithSessionSelection,
	InteractiveMode,
	type InteractiveModeOptions,
	type IrohRemoteAgentRuntimeOptions,
	type IrohRemoteAgentRuntimeResult,
	type IrohRemoteAgentRuntimeSessionSelection,
	type IrohRemoteSubagentRuntimeCreatedEvent,
	type PrintModeOptions,
	type RpcModeOptions,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
export {
	DEFAULT_INTEGRATED_DETACHED_RUNTIME_TTL_MS,
	type DetachedRuntimeRetentionHandle,
	type DetachedRuntimeRetentionOptions,
	parseIntegratedDetachedRuntimeTtlMs,
	scheduleDetachedRuntimeRetention,
} from "./remote/integrated-runtime-retention.ts";
export {
	DEFAULT_STORE_CATALOG_URL,
	findCatalogPackage,
	getStoreCatalogCachePath,
	type LoadDefaultStoreCatalogOptions,
	type LoadStoreCatalogResult,
	loadDefaultStoreCatalog,
	parseStoreCatalogJson,
	STORE_CATALOG_SCHEMA_VERSION,
	type StoreCatalog,
	type StoreCatalogFetcher,
	type StoreCatalogPackage,
	type StoreCatalogReview,
	type StoreCatalogValidationResult,
	type StoreResourceType,
	searchCatalogPackages,
	suggestCatalogPackageIds,
	validateStoreCatalog,
} from "./store/catalog.ts";
export {
	type InspectStorePackageOptions,
	inspectPackageDirectory,
	inspectStorePackage,
	type StorePackageInspection,
	type StoreVoltField,
} from "./store/inspector.ts";
export {
	type BuildStoreInstallPlanOptions,
	buildStoreInstallPlan,
	getCompatibilityStatus,
	type StoreCompatibilityStatus,
	type StoreInstallPlan,
	type StoreInstallScope,
	type StoreInstallScriptPolicy,
} from "./store/install-plan.ts";
export {
	type ResolveStoreSourceOptions,
	resolveStoreSource,
	type StoreGitLsRemote,
	type StoreResolvedSource,
	type StoreResolvedSourceKind,
} from "./store/resolver.ts";
export {
	chooseStoreRemoveTarget,
	chooseStoreUpdateTarget,
	getMatchingStorePackageScopes,
	type StoreScopeTarget,
	type StoreTargetConflict,
	type StoreTargetPackageManager,
	type StoreTargetSelection,
} from "./store/targets.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
