// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export { getAgentDir, getDocsPath, getExamplesPath, getPackageDir, getReadmePath, VERSION } from "./config.ts";
export {
	type ActiveCompaction,
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type CompactionReason,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateMessagesTokens,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WebSearchToolCallEvent,
	WebSearchToolResultEvent,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWebSearchToolResult,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export type {
	HostActionDecision,
	HostActionDecisionKind,
	HostActionMetadata,
	HostActionMetadataValue,
	HostActionRequest,
	HostActionStatus,
	HostActionUpdate,
	HostInteraction,
} from "./core/host-interaction.ts";
// LSP
export {
	installHintForCommand,
	installRecipeForCommand,
	LspClient,
	type LspClientOptions,
	type LspDiagnostic,
	type LspInstallCommandOptions,
	type LspInstallCommandResult,
	type LspInstallRecipe,
	type LspInstallRunner,
	LspManager,
	type LspManagerOptions,
	type LspServerSettings,
	type LspServerStatus,
	type LspSettings,
	type LspSeverity,
	type LspTraceDirection,
	LspTracer,
	languageIdForExtension,
	type ResolvedLspConfig,
	type ResolvedLspServerConfig,
	resolveLspConfig,
	runDefaultLspInstallCommand,
} from "./core/lsp/index.ts";
export {
	createMcpDirectToolDefinitions,
	DEFAULT_MCP_SETTINGS,
	DefaultMcpClientFactory,
	finalizeMcpConfig,
	getMcpRpcCapabilities,
	hasProjectMcpConfig,
	listMcpRpcServers,
	loadMcpConfig,
	McpAuditLogger,
	type McpAuthConfig,
	type McpClientFactory,
	type McpConfigDiagnostic,
	type McpDirectToolCandidate,
	type McpDirectToolDetails,
	type McpGatewayCallResult,
	type McpGatewayInput,
	type McpGatewayToolDetails,
	type McpGatewayToolInput,
	type McpGatewayToolOptions,
	McpManager,
	McpMetadataCache,
	type McpOAuthBrowserCompleteResult,
	type McpOAuthBrowserStartResult,
	type McpOAuthDevicePollResult,
	type McpOAuthDeviceStartResult,
	McpOAuthStore,
	type McpOAuthStoredRecord,
	McpOutputStore,
	type McpResolvedConfig,
	type McpResolvedServerConfig,
	type McpRpcCapabilities,
	type McpServerSummary,
	type McpSettings,
	type McpToolSummary,
	searchMcpMetadata,
} from "./core/mcp/index.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageInstallOptions,
	PackageInstallScriptPolicy,
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export {
	type AuthorizeIrohRemoteClientOptions,
	assertIrohRemoteHandshakeHostIdentity,
	assertIrohRemoteTicketNotExpired,
	assertIrohRemoteTicketPayloadHostIdentity,
	authorizeIrohRemoteClient,
	type CreateIrohRemoteHostMetadataOptions,
	cloneIrohRemoteRpcGrant,
	createEmptyIrohRemoteHostState,
	createIrohRemoteExplicitAccess,
	createIrohRemoteFilteredRpcTransport,
	createIrohRemoteHandshakeFailure,
	createIrohRemoteHandshakeSuccess,
	createIrohRemoteHostMetadata,
	createIrohRemoteOutboundFilteredRpcTransport,
	createIrohRemotePresetAccess,
	createIrohRemoteRpcCapabilityDeniedResponse,
	createIrohRemoteRpcErrorResponse,
	createIrohRemoteRpcGrant,
	createIrohRemoteRpcTransport,
	createIrohRemoteSanitizedReconnectTicket,
	createIrohRemoteSanitizedReconnectTicketPayload,
	createIrohRemoteTicketQrCode,
	DEFAULT_IROH_REMOTE_ALLOW_TOOLS,
	DEFAULT_IROH_REMOTE_CONTROL_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_DEVICE_LOG_MAX_CONTENT_BYTES,
	DEFAULT_IROH_REMOTE_HANDSHAKE_MAX_LINE_BYTES,
	DEFAULT_IROH_REMOTE_HANDSHAKE_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_PAIRING_SECRET_TOMBSTONE_RETENTION_MS,
	DEFAULT_IROH_REMOTE_PAIRING_TICKET_TTL_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_RETRY_ATTEMPTS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_RETRY_DELAY_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_PUSH_RELAY_URL,
	decodeIrohRemoteTicketPayload,
	encodeIrohRemoteTicketPayload,
	ensureIrohRemoteControlDirectory,
	findIrohRemoteClient,
	findIrohRemoteRevokedClient,
	formatIrohRemoteHostFingerprint,
	formatIrohRemoteTicketQrCode,
	formatIrohRemoteTicketQrCodeTerminal,
	getAvailableIrohRemoteWorkspaceNames,
	getIrohRemoteAccessPreset,
	getIrohRemoteControlPath,
	getIrohRemotePairingVerificationDetails,
	getIrohRemoteRpcCommandCapabilities,
	getIrohRemoteRpcFilterResult,
	getIrohRemoteStreamCapability,
	getIrohRemoteUnsafeAllowedTools,
	getIrohRemoteWorkspaceAvailabilityStatus,
	getIrohRemoteWorkspaceStatuses,
	getMissingIrohRemoteRpcCapability,
	getStaticIrohRemoteRpcFilterResult,
	type HandleIrohRemoteDeviceLogUploadRpcCommandOptions,
	type HandleIrohRemoteWorkspaceUnregisterRpcCommandOptions,
	type HandleIrohRemoteWorktreeRpcCommandOptions,
	handleIrohRemoteDeviceLogUploadRpcCommand,
	handleIrohRemoteWorkspaceUnregisterRpcCommand,
	handleIrohRemoteWorktreeRpcCommand,
	hashIrohRemotePairingSecret,
	hashIrohRemotePushToken,
	hasIrohRemoteRpcCapability,
	IROH_REMOTE_ACCESS_PRESET_NAMES,
	IROH_REMOTE_ACCESS_PRESETS,
	IROH_REMOTE_ALPN,
	IROH_REMOTE_CONVERSATION_STREAMS_FEATURE,
	IROH_REMOTE_CREATE_WORKTREE_RPC_TYPE,
	IROH_REMOTE_DEVICE_LOGS_DIR_SEGMENTS,
	IROH_REMOTE_HANDSHAKE_TYPE,
	IROH_REMOTE_HELLO_TYPE,
	IROH_REMOTE_HOST_FEATURES,
	IROH_REMOTE_HOST_HANDSHAKE_FAILURE_OUTCOMES,
	IROH_REMOTE_LIST_WORKTREES_RPC_TYPE,
	IROH_REMOTE_MULTI_STREAMS_FEATURE,
	IROH_REMOTE_OUTCOMES,
	IROH_REMOTE_PAIR_CONTROL_REQUEST_TYPE,
	IROH_REMOTE_PAIR_CONTROL_RESPONSE_TYPE,
	IROH_REMOTE_REDACTED_BASH_OUTPUT_PATH,
	IROH_REMOTE_REDACTED_EXPORT_PATH,
	IROH_REMOTE_REDACTED_SESSION_FILE,
	IROH_REMOTE_REMOVE_WORKTREE_RPC_TYPE,
	IROH_REMOTE_REVOKE_CONTROL_REQUEST_TYPE,
	IROH_REMOTE_REVOKE_CONTROL_RESPONSE_TYPE,
	IROH_REMOTE_RPC_CANCELLATION_TYPES,
	IROH_REMOTE_RPC_CAPABILITIES,
	IROH_REMOTE_RPC_GRANT_SCHEMA_VERSION,
	IROH_REMOTE_RPC_PASSTHROUGH_TYPES,
	IROH_REMOTE_SESSION_ID_PATTERN,
	IROH_REMOTE_SESSION_RUNTIME_STATE_FEATURE,
	IROH_REMOTE_TICKET_PREFIX,
	IROH_REMOTE_UNREGISTER_WORKSPACE_RPC_TYPE,
	IROH_REMOTE_UNSAFE_TOOL_NAMES,
	IROH_REMOTE_UPLOAD_DEVICE_LOGS_RPC_TYPE,
	IROH_REMOTE_WORKSPACE_HAS_WORKTREES_ERROR,
	IROH_REMOTE_WORKTREE_ID_PATTERN,
	IROH_REMOTE_WORKTREE_RPC_TYPES,
	IROH_REMOTE_WORKTREES_FEATURE,
	type IrohRemoteAccessPreset,
	type IrohRemoteAccessPresetName,
	type IrohRemoteActiveStreamEntry,
	IrohRemoteActiveStreamRegistry,
	type IrohRemoteAuditEvent,
	type IrohRemoteAuditEventInput,
	IrohRemoteAuditLogger,
	type IrohRemoteAuditLoggerOptions,
	type IrohRemoteAuditSink,
	type IrohRemoteClient,
	type IrohRemoteClientAccessUpdateResult,
	type IrohRemoteClientAuthorizationFailure,
	type IrohRemoteClientAuthorizationResult,
	type IrohRemoteClientAuthorizationSuccess,
	IrohRemoteClientEngine,
	type IrohRemoteClientEngineOptions,
	type IrohRemoteClientHandshakeResponseResult,
	type IrohRemoteClientReadHandshakeResponseOptions,
	type IrohRemoteClientRePairApprovalResult,
	type IrohRemoteClientRevocationResult,
	type IrohRemoteClientTicketHello,
	type IrohRemoteControlClientOptions,
	type IrohRemoteControlRequest,
	type IrohRemoteControlServerListenOptions,
	type IrohRemoteConversationHandshakeMetadata,
	type IrohRemoteConversationSelection,
	type IrohRemoteConversationTarget,
	type IrohRemoteDeviceLogUploadRpcData,
	type IrohRemoteDeviceLogUploadRpcResponse,
	type IrohRemoteFilteredRpcTransportOptions,
	type IrohRemoteGrantedClient,
	type IrohRemoteGrantedPendingPairingTicket,
	type IrohRemoteGrantedRevokedClient,
	IrohRemoteHandshakeError,
	type IrohRemoteHandshakeFailure,
	type IrohRemoteHandshakeLineReadOptions,
	type IrohRemoteHandshakeLineReadResult,
	type IrohRemoteHandshakeResponse,
	type IrohRemoteHandshakeSuccess,
	type IrohRemoteHello,
	type IrohRemoteHelloMode,
	IrohRemoteHostEngine,
	type IrohRemoteHostEngineOptions,
	type IrohRemoteHostFeature,
	type IrohRemoteHostHandshakeFailureOutcome,
	type IrohRemoteHostHandshakeMetadata,
	type IrohRemoteHostHandshakeResult,
	type IrohRemoteHostMetadata,
	type IrohRemoteHostPairOptions,
	type IrohRemoteHostReadHandshakeOptions,
	type IrohRemoteHostState,
	IrohRemoteHostStateManager,
	type IrohRemoteHostStateManagerOptions,
	IrohRemoteInMemoryPushNotificationDeduper,
	type IrohRemoteLiveActivityContentState,
	type IrohRemoteLiveActivityDeliveryChannelLookup,
	type IrohRemoteLiveActivityRegistration,
	type IrohRemoteLiveActivityRegistrationResult,
	type IrohRemoteLiveActivityTarget,
	type IrohRemoteLiveActivityToolGlyph,
	type IrohRemoteLiveActivityUpdateIntent,
	type IrohRemoteOutboundFilterOptions,
	type IrohRemoteOutboundJsonlReadablePipeOptions,
	type IrohRemoteOutboundSanitizerOptions,
	type IrohRemoteOutboundValueDecorator,
	type IrohRemoteOutcome,
	IrohRemoteOutcomeError,
	type IrohRemotePairControlClientOptions,
	type IrohRemotePairControlRequest,
	type IrohRemotePairControlResponse,
	type IrohRemotePairingSecretTombstone,
	type IrohRemotePairingSecretTombstoneOutcome,
	type IrohRemotePairingTicket,
	type IrohRemotePairingVerificationDetails,
	type IrohRemotePendingPairingTicket,
	type IrohRemotePushNotificationDeduper,
	type IrohRemotePushNotificationDelivery,
	type IrohRemotePushNotificationDeliveryStatus,
	IrohRemotePushNotificationDispatcher,
	type IrohRemotePushNotificationDispatcherOptions,
	type IrohRemotePushNotificationIntent,
	type IrohRemotePushRelayClient,
	IrohRemotePushRelayHttpClient,
	type IrohRemotePushRelayHttpClientOptions,
	IrohRemotePushRelayHttpError,
	type IrohRemotePushRelayLiveActivityRequest,
	type IrohRemotePushRelayNotificationRequest,
	type IrohRemotePushRelayNotificationResult,
	type IrohRemotePushTarget,
	type IrohRemotePushTargetPlatform,
	type IrohRemotePushTargetProvider,
	type IrohRemotePushTargetRegistrationRequest,
	type IrohRemotePushTargetRegistrationResult,
	type IrohRemotePushTokenEnvironment,
	type IrohRemoteRelayMode,
	type IrohRemoteRevokeControlClientOptions,
	type IrohRemoteRevokeControlRequest,
	type IrohRemoteRevokeControlResponse,
	type IrohRemoteRevokedClient,
	type IrohRemoteRpcCapability,
	type IrohRemoteRpcCapabilityDeniedError,
	type IrohRemoteRpcCapabilityDeniedResponse,
	type IrohRemoteRpcCommand,
	type IrohRemoteRpcErrorResponse,
	type IrohRemoteRpcFilterResult,
	type IrohRemoteRpcGrant,
	type IrohRemoteRuntimeToolPolicy,
	type IrohRemoteSanitizedReconnectTicketPayload,
	type IrohRemoteSanitizedTranscriptText,
	type IrohRemoteTicketPayload,
	type IrohRemoteTicketQrCode,
	type IrohRemoteTicketQrCodeFormatOptions,
	type IrohRemoteTranscriptTextLayout,
	type IrohRemoteUnsafeApproval,
	type IrohRemoteWorkspace,
	type IrohRemoteWorkspaceAvailabilityClassifier,
	type IrohRemoteWorkspaceAvailabilityStatus,
	type IrohRemoteWorkspaceDiscoveryTarget,
	IrohRemoteWorkspaceHasWorktreesError,
	type IrohRemoteWorkspaceManagementTarget,
	type IrohRemoteWorkspaceMetadataSnapshot,
	type IrohRemoteWorkspaceStatus,
	type IrohRemoteWorkspaceTrustStore,
	type IrohRemoteWorkspaceUnregisterRpcData,
	type IrohRemoteWorkspaceUnregisterRpcResponse,
	type IrohRemoteWorkspaceUnregisterRpcResult,
	type IrohRemoteWorkspaceWorktree,
	type IrohRemoteWorktreeRpcBackend,
	type IrohRemoteWorktreeRpcResponse,
	type IrohRemoteWorktreeRpcResult,
	type IrohRemoteWorktreeSummary,
	isIrohRemoteAccessPresetName,
	isIrohRemoteClientAllowedForWorkspace,
	isIrohRemoteHostHandshakeFailureOutcome,
	isIrohRemoteOutcome,
	isIrohRemoteRelayMode,
	isIrohRemoteRuntimeToolPolicyWithin,
	isIrohRemoteSessionId,
	isIrohRemoteWorkspaceHasWorktreesError,
	isIrohRemoteWorkspaceName,
	isIrohRemoteWorktreeId,
	listenIrohRemoteControlServer,
	normalizeIrohRemoteAllowTools,
	parseIrohRemoteAllowTools,
	parseIrohRemoteClient,
	parseIrohRemoteControlRequest,
	parseIrohRemoteHandshakeResponse,
	parseIrohRemoteHandshakeResponseLine,
	parseIrohRemoteHello,
	parseIrohRemoteHelloLine,
	parseIrohRemoteHostState,
	parseIrohRemoteLiveActivityRegistration,
	parseIrohRemotePairControlRequest,
	parseIrohRemotePairControlResponse,
	parseIrohRemotePairingSecretTombstone,
	parseIrohRemotePendingPairingTicket,
	parseIrohRemotePushTarget,
	parseIrohRemoteRevokeControlRequest,
	parseIrohRemoteRevokeControlResponse,
	parseIrohRemoteRevokedClient,
	parseIrohRemoteRpcCapabilities,
	parseIrohRemoteRpcGrant,
	parseIrohRemoteTicketPayload,
	parseIrohRemoteWorkspace,
	parseIrohRemoteWorkspaceSpec,
	parseIrohRemoteWorkspaceWorktree,
	parseRegisterPushTargetArgs,
	pipeIrohRemoteOutboundJsonlReadable,
	type ResolveIrohRemoteRuntimeToolPolicyOptions,
	type ResolveIrohRemoteWorkspaceProjectTrustOptions,
	readIrohRemoteHandshakeLine,
	readIrohRemoteHostState,
	requestIrohRemoteActiveRevocation,
	requestIrohRemotePairingTicket,
	resolveIrohRemoteRuntimeToolPolicy,
	resolveIrohRemoteWorkspaceProjectTrusted,
	sanitizeIrohRemoteOutbound,
	sanitizeIrohRemoteOutboundJsonLine,
	sanitizeIrohRemoteTranscriptText,
	selectIrohRemoteWorkspace,
	serializeIrohRemoteRpcFilterRejection,
	shouldReplaceIrohRemoteIntegratedRuntimeForAuthorization,
	upsertIrohRemoteWorkspace,
	usesDefaultIrohRemoteAllowTools,
	writeIrohRemoteHandshakeResponse,
	writeIrohRemoteHello,
	writeIrohRemoteHostState,
} from "./core/remote/iroh/index.ts";
export type {
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
	ResourceLoaderSubagentsResult,
} from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
export {
	attachJsonlLineReader,
	createIrohRpcTransport,
	createJsonlRpcTransport,
	createJsonlStreamRpcTransport,
	createLoopbackRpcTransportPair,
	DEFAULT_IROH_READ_LIMIT,
	DEFAULT_IROH_RPC_MAX_LINE_BYTES,
	type IrohBiStreamLike,
	type IrohBytes,
	type IrohRecvStreamLike,
	type IrohRpcTransportOptions,
	type IrohSendStreamLike,
	type JsonlRpcTransportOptions,
	type JsonlStreamRpcTransportOptions,
	type LoopbackRpcTransportPair,
	type RpcCloseHandler,
	type RpcLineHandler,
	type RpcTransport,
	serializeJsonLine,
} from "./core/rpc/index.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createSubagentRegistryTool,
	createSubagentTool,
	createWebSearchTool,
	createWriteTool,
	type PromptTemplate,
	type SubagentRuntimeContext,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getDefaultSessionDir,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type ImageSettings,
	type PackageSource,
	type ProfileSettings,
	type ProfileStorageSettings,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export {
	createBuiltInSubagentDefinitions,
	type DiscoverSubagentDefinitionsOptions,
	discoverSubagentDefinitions,
	type FileSubagentDefinitionSource,
	type ParseSubagentDefinitionOptions,
	type ParseSubagentDefinitionResult,
	parseSubagentDefinition,
	type SubagentActivity,
	type SubagentActivityEvent,
	type SubagentActivityListener,
	type SubagentActivityStatus,
	type SubagentDefinition,
	SubagentDefinitionConfigurationError,
	SubagentDefinitionNotFoundError,
	type SubagentDefinitionSource,
	SubagentDelegationScope,
	type SubagentDelegationScopeLease,
	type SubagentDelegationScopeOptions,
	type SubagentDelegationScopeSnapshot,
	type SubagentDiscoveryResult,
	type SubagentEndEvent,
	type SubagentEvent,
	type SubagentEventListener,
	type SubagentHandle,
	SubagentManager,
	type SubagentManagerOptions,
	type SubagentResult,
	type SubagentRuntimeCreatedEvent,
	type SubagentStartByNameOptions,
	type SubagentStartOptions,
} from "./core/subagents/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./core/theme/runtime.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createDefaultWebSearchOperations,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLspToolDefinition,
	createLsToolDefinition,
	createMcpTool,
	createMcpToolDefinition,
	createReadToolDefinition,
	createSubagentRegistryToolDefinition,
	createSubagentToolDefinition,
	createWebSearchToolDefinition,
	createWriteToolDefinition,
	DEFAULT_ACTIVE_TOOL_NAMES,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	DEFAULT_SUBAGENT_AGGREGATE_OUTPUT_MAX_BYTES,
	DEFAULT_SUBAGENT_OUTPUT_MAX_BYTES,
	type DefaultWebSearchOperationsOptions,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LspAction,
	type LspNavigationProvider,
	type LspToolDetails,
	type LspToolInput,
	type LspToolOptions,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	READ_ONLY_TOOL_NAMES,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	SUBAGENT_REGISTRY_TOOL_NAME,
	type SubagentRegistryToolInput,
	type SubagentRegistryToolOptions,
	type SubagentToolDetails,
	type SubagentToolInput,
	type SubagentToolManager,
	type SubagentToolOptions,
	type SubagentToolStatus,
	type SubagentToolUsageDetails,
	type ToolDiagnosticsProvider,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WebSearchFetcher,
	type WebSearchModelContext,
	type WebSearchModelContextProvider,
	type WebSearchOperations,
	type WebSearchRequest,
	type WebSearchResponse,
	type WebSearchResult,
	type WebSearchToolDetails,
	type WebSearchToolInput,
	type WebSearchToolOptions,
	type WriteOperations,
	type WriteToolDetails,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	createInProcessRpcClient,
	createIrohRemoteAgentRuntime,
	createIrohRemoteAgentRuntimeWithSessionSelection,
	InProcessRpcClient,
	type InProcessRpcClientEventListener,
	type InProcessRpcClientOptions,
	InteractiveMode,
	type InteractiveModeOptions,
	type IrohRemoteAgentRuntimeOptions,
	type IrohRemoteAgentRuntimeResult,
	type IrohRemoteAgentRuntimeSessionSelection,
	type IrohRemoteCompletedCommand,
	type IrohRemoteCompletionState,
	type IrohRemoteNotificationKind,
	type IrohRemoteNotificationRequest,
	type IrohRemoteRpcModeOptions,
	type IrohRemoteSubagentRuntimeCreatedEvent,
	type ModelInfo,
	type PrintModeOptions,
	type RpcActiveCompaction,
	type RpcActiveToolExecution,
	RpcClient,
	type RpcClientCapabilityFeature,
	type RpcClientEvent,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionErrorEvent,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcHostActionRequest,
	type RpcHostActionResponse,
	type RpcHostActionUpdate,
	type RpcListSubagentsResponse,
	type RpcMcpCapabilitiesResponse,
	type RpcMcpPromptContentResponse,
	type RpcMcpPromptsResponse,
	type RpcMcpRecentCallsResponse,
	type RpcMcpResourceContentResponse,
	type RpcMcpResourcesResponse,
	type RpcMcpServerResponse,
	type RpcMcpServersResponse,
	type RpcMcpToolResponse,
	type RpcMcpToolsResponse,
	type RpcModeOptions,
	type RpcPendingHostActionsResponse,
	type RpcPushPlatform,
	type RpcPushProvider,
	type RpcRegisterPushTargetArgs,
	type RpcRegisterPushTargetResponse,
	type RpcResponse,
	type RpcSessionChange,
	type RpcSessionListItem,
	type RpcSessionState,
	type RpcSubagentDefinition,
	type RpcSubagentDefinitionSource,
	type RpcSubagentEndEvent,
	type RpcSubagentEvent,
	type RpcSubagentSourceInfo,
	type RpcSubagentStartResponse,
	type RpcTranscriptItem,
	type RpcTranscriptResponse,
	type RpcTranscriptToolStatus,
	RpcTransportClient,
	type RpcTransportClientOptions,
	type RpcWorkflowEvent,
	type RpcWorkflowKind,
	type RpcWorkflowStatus,
	type RpcWorkflowToolEvent,
	runIrohRemoteRpcMode,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
export {
	DEFAULT_INTEGRATED_DETACHED_RUNTIME_TTL_MS,
	type DetachedRuntimeRetentionHandle,
	type DetachedRuntimeRetentionOptions,
	parseIntegratedDetachedRuntimeTtlMs,
	scheduleDetachedRuntimeRetention,
} from "./remote/integrated-runtime-retention.ts";
export {
	DEFAULT_STORE_CATALOG_URL,
	findCatalogPackage,
	getStoreCatalogCachePath,
	type LoadDefaultStoreCatalogOptions,
	type LoadStoreCatalogResult,
	loadDefaultStoreCatalog,
	parseStoreCatalogJson,
	type StoreCatalog,
	type StoreCatalogFetcher,
	type StoreCatalogPackage,
	type StoreCatalogValidationResult,
	type StoreResourceType,
	searchCatalogPackages,
	suggestCatalogPackageIds,
	validateStoreCatalog,
} from "./store/catalog.ts";
export {
	type InspectStorePackageOptions,
	inspectPackageDirectory,
	inspectStorePackage,
	type StorePackageInspection,
	type StoreVoltManifest,
} from "./store/inspector.ts";
export {
	type BuildStoreInstallPlanOptions,
	buildStoreInstallPlan,
	getCompatibilityStatus,
	type StoreCompatibilityStatus,
	type StoreInstallPlan,
	type StoreInstallScope,
	type StoreInstallScriptPolicy,
} from "./store/install-plan.ts";
export {
	type ResolveStoreSourceOptions,
	resolveStoreSource,
	type StoreGitLsRemote,
	type StoreResolvedSource,
	type StoreResolvedSourceKind,
} from "./store/resolver.ts";
export {
	chooseStoreRemoveTarget,
	chooseStoreUpdateTarget,
	getMatchingStorePackageScopes,
	type StoreScopeTarget,
	type StoreTargetConflict,
	type StoreTargetPackageManager,
	type StoreTargetSelection,
} from "./store/targets.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
