// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export { getAgentDir, getDocsPath, getExamplesPath, getPackageDir, getReadmePath, VERSION } from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
// LSP
export {
	LspClient,
	type LspClientOptions,
	type LspDiagnostic,
	LspManager,
	type LspManagerOptions,
	type LspServerSettings,
	type LspServerStatus,
	type LspSettings,
	type LspSeverity,
	type LspTraceDirection,
	LspTracer,
	languageIdForExtension,
	type ResolvedLspConfig,
	type ResolvedLspServerConfig,
	resolveLspConfig,
} from "./core/lsp/index.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageInstallOptions,
	PackageInstallScriptPolicy,
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export {
	type AuthorizeIrohRemoteClientOptions,
	assertIrohRemoteTicketNotExpired,
	authorizeIrohRemoteClient,
	createEmptyIrohRemoteHostState,
	createIrohRemoteFilteredRpcTransport,
	createIrohRemoteHandshakeFailure,
	createIrohRemoteHandshakeSuccess,
	createIrohRemoteOutboundFilteredRpcTransport,
	createIrohRemoteRpcErrorResponse,
	createIrohRemoteRpcTransport,
	DEFAULT_IROH_REMOTE_ALLOW_TOOLS,
	DEFAULT_IROH_REMOTE_HANDSHAKE_MAX_LINE_BYTES,
	DEFAULT_IROH_REMOTE_HANDSHAKE_TIMEOUT_MS,
	DEFAULT_IROH_REMOTE_PAIRING_TICKET_TTL_MS,
	decodeIrohRemoteTicketPayload,
	encodeIrohRemoteTicketPayload,
	findIrohRemoteClient,
	getIrohRemoteRpcFilterResult,
	IROH_REMOTE_ALPN,
	IROH_REMOTE_HANDSHAKE_TYPE,
	IROH_REMOTE_HELLO_TYPE,
	IROH_REMOTE_REDACTED_BASH_OUTPUT_PATH,
	IROH_REMOTE_REDACTED_EXPORT_PATH,
	IROH_REMOTE_REDACTED_HOST_PATH,
	IROH_REMOTE_REDACTED_SESSION_FILE,
	IROH_REMOTE_RPC_PASSTHROUGH_TYPES,
	IROH_REMOTE_TICKET_PREFIX,
	type IrohRemoteAuditEvent,
	type IrohRemoteAuditEventInput,
	IrohRemoteAuditLogger,
	type IrohRemoteAuditLoggerOptions,
	type IrohRemoteAuditSink,
	type IrohRemoteClient,
	type IrohRemoteClientAuthorizationFailure,
	type IrohRemoteClientAuthorizationResult,
	type IrohRemoteClientAuthorizationSuccess,
	IrohRemoteClientEngine,
	type IrohRemoteClientEngineOptions,
	type IrohRemoteClientHandshakeResponseResult,
	type IrohRemoteClientRevocationResult,
	type IrohRemoteClientTicketHello,
	type IrohRemoteFilteredRpcTransportOptions,
	type IrohRemoteHandshakeFailure,
	type IrohRemoteHandshakeLineReadOptions,
	type IrohRemoteHandshakeLineReadResult,
	type IrohRemoteHandshakeResponse,
	type IrohRemoteHandshakeSuccess,
	type IrohRemoteHello,
	IrohRemoteHostEngine,
	type IrohRemoteHostEngineOptions,
	type IrohRemoteHostHandshakeResult,
	type IrohRemoteHostPairOptions,
	type IrohRemoteHostReadHandshakeOptions,
	type IrohRemoteHostState,
	IrohRemoteHostStateManager,
	type IrohRemoteHostStateManagerOptions,
	type IrohRemoteOutboundFilterOptions,
	type IrohRemoteOutboundJsonlReadablePipeOptions,
	type IrohRemoteOutboundSanitizerOptions,
	type IrohRemotePairingTicket,
	type IrohRemoteRelayMode,
	type IrohRemoteRpcCommand,
	type IrohRemoteRpcErrorResponse,
	type IrohRemoteRpcFilterResult,
	type IrohRemoteTicketPayload,
	type IrohRemoteWorkspace,
	isIrohRemoteClientAllowedForWorkspace,
	isIrohRemoteRelayMode,
	parseIrohRemoteClient,
	parseIrohRemoteHandshakeResponse,
	parseIrohRemoteHandshakeResponseLine,
	parseIrohRemoteHello,
	parseIrohRemoteHelloLine,
	parseIrohRemoteHostState,
	parseIrohRemoteTicketPayload,
	parseIrohRemoteWorkspace,
	parseIrohRemoteWorkspaceSpec,
	pipeIrohRemoteOutboundJsonlReadable,
	readIrohRemoteHandshakeLine,
	readIrohRemoteHostState,
	sanitizeIrohRemoteOutbound,
	sanitizeIrohRemoteOutboundJsonLine,
	selectIrohRemoteWorkspace,
	serializeIrohRemoteRpcFilterRejection,
	upsertIrohRemoteWorkspace,
	writeIrohRemoteHandshakeResponse,
	writeIrohRemoteHello,
	writeIrohRemoteHostState,
} from "./core/remote/iroh/index.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
export {
	attachJsonlLineReader,
	createIrohRpcTransport,
	createJsonlRpcTransport,
	createJsonlStreamRpcTransport,
	createLoopbackRpcTransportPair,
	DEFAULT_IROH_READ_LIMIT,
	type IrohBiStreamLike,
	type IrohBytes,
	type IrohRecvStreamLike,
	type IrohRpcTransportOptions,
	type IrohSendStreamLike,
	type JsonlRpcTransportOptions,
	type JsonlStreamRpcTransportOptions,
	type LoopbackRpcTransportPair,
	type RpcCloseHandler,
	type RpcLineHandler,
	type RpcTransport,
	serializeJsonLine,
} from "./core/rpc/index.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type ImageSettings,
	type PackageSource,
	type ProfileSettings,
	type ProfileStorageSettings,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLspToolDefinition,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LspAction,
	type LspNavigationProvider,
	type LspToolDetails,
	type LspToolInput,
	type LspToolOptions,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolDiagnosticsProvider,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolDetails,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	createInProcessRpcClient,
	createIrohRemoteAgentRuntime,
	InProcessRpcClient,
	type InProcessRpcClientEventListener,
	type InProcessRpcClientOptions,
	InteractiveMode,
	type InteractiveModeOptions,
	type IrohRemoteAgentRuntimeOptions,
	type IrohRemoteRpcModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientEvent,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionErrorEvent,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcModeOptions,
	type RpcResponse,
	type RpcSessionState,
	RpcTransportClient,
	type RpcTransportClientOptions,
	runIrohRemoteRpcMode,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
export {
	DEFAULT_STORE_CATALOG_URL,
	findCatalogPackage,
	getStoreCatalogCachePath,
	type LoadDefaultStoreCatalogOptions,
	type LoadStoreCatalogResult,
	loadDefaultStoreCatalog,
	parseStoreCatalogJson,
	type StoreCatalog,
	type StoreCatalogFetcher,
	type StoreCatalogPackage,
	type StoreCatalogValidationResult,
	type StoreResourceType,
	searchCatalogPackages,
	suggestCatalogPackageIds,
	validateStoreCatalog,
} from "./store/catalog.ts";
export {
	type InspectStorePackageOptions,
	inspectPackageDirectory,
	inspectStorePackage,
	type StorePackageInspection,
	type StoreVoltManifest,
} from "./store/inspector.ts";
export {
	type BuildStoreInstallPlanOptions,
	buildStoreInstallPlan,
	getCompatibilityStatus,
	type StoreCompatibilityStatus,
	type StoreInstallPlan,
	type StoreInstallScope,
	type StoreInstallScriptPolicy,
} from "./store/install-plan.ts";
export {
	type ResolveStoreSourceOptions,
	resolveStoreSource,
	type StoreGitLsRemote,
	type StoreResolvedSource,
	type StoreResolvedSourceKind,
} from "./store/resolver.ts";
export {
	chooseStoreRemoveTarget,
	chooseStoreUpdateTarget,
	getMatchingStorePackageScopes,
	type StoreScopeTarget,
	type StoreTargetConflict,
	type StoreTargetPackageManager,
	type StoreTargetSelection,
} from "./store/targets.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
