/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
	type SubagentRuntimeContext,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export type {
	HostActionDecision,
	HostActionDecisionKind,
	HostActionMetadata,
	HostActionMetadataValue,
	HostActionRequest,
	HostActionStatus,
	HostActionUpdate,
	HostInteraction,
} from "./host-interaction.ts";
export * from "./mcp/index.ts";
export * from "./remote/iroh/index.ts";
export {
	attachJsonlLineReader,
	createIrohRpcTransport,
	createJsonlRpcTransport,
	createJsonlStreamRpcTransport,
	createLoopbackRpcTransportPair,
	DEFAULT_IROH_READ_LIMIT,
	type IrohBiStreamLike,
	type IrohBytes,
	type IrohRecvStreamLike,
	type IrohRpcTransportOptions,
	type IrohSendStreamLike,
	type JsonlRpcTransportOptions,
	type JsonlStreamRpcTransportOptions,
	type LoopbackRpcTransportPair,
	type RpcClientCapabilityFeature,
	type RpcCloseHandler,
	type RpcCommand,
	type RpcCommandType,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcHostActionRequest,
	type RpcHostActionResponse,
	type RpcHostActionUpdate,
	type RpcLineHandler,
	type RpcListSubagentsResponse,
	type RpcMcpCapabilitiesResponse,
	type RpcMcpRecentCallsResponse,
	type RpcMcpServerResponse,
	type RpcMcpServersResponse,
	type RpcModel,
	type RpcPendingHostActionsResponse,
	type RpcResponse,
	type RpcSessionState,
	type RpcSlashCommand,
	type RpcSubagentDefinition,
	type RpcSubagentDefinitionSource,
	type RpcSubagentSourceInfo,
	type RpcSubagentStartResponse,
	type RpcTransport,
	serializeJsonLine,
} from "./rpc/index.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
export {
	createBuiltInSubagentDefinitions,
	type DiscoverSubagentDefinitionsOptions,
	discoverSubagentDefinitions,
	type FileSubagentDefinitionSource,
	type ParseSubagentDefinitionOptions,
	type ParseSubagentDefinitionResult,
	parseSubagentDefinition,
	type SubagentActivity,
	type SubagentActivityEvent,
	type SubagentActivityListener,
	type SubagentActivityStatus,
	type SubagentDefinition,
	SubagentDefinitionConfigurationError,
	SubagentDefinitionNotFoundError,
	type SubagentDefinitionSource,
	type SubagentDiscoveryResult,
	type SubagentEndEvent,
	type SubagentEvent,
	type SubagentEventListener,
	type SubagentHandle,
	SubagentManager,
	type SubagentManagerOptions,
	type SubagentResult,
	type SubagentStartByNameOptions,
	type SubagentStartOptions,
} from "./subagents/index.ts";
