import type { BuiltinIntentName } from "@hansjm10/volt-protocol";
import {
	abortBashIntent,
	abortIntent,
	abortRetryIntent,
	bashIntent,
	cloneIntent,
	compactIntent,
	exportHtmlIntent,
	followUpIntent,
	forkIntent,
	newSessionIntent,
	planChangeIntent,
	planDiscardIntent,
	planExecuteIntent,
	promptIntent,
	setAgentModeIntent,
	setFastModeIntent,
	setModelIntent,
	setSessionNameIntent,
	setThinkingLevelIntent,
	steerIntent,
	switchSessionIntent,
} from "./conversation.ts";
import {
	createWorktreeIntent,
	mcpAuthCancelIntent,
	mcpAuthCompleteIntent,
	mcpAuthPollIntent,
	mcpAuthStartBrowserIntent,
	mcpAuthStartDeviceIntent,
	mcpConnectIntent,
	mcpDisconnectIntent,
	mcpLogoutIntent,
	mcpRefreshIntent,
	mcpSetEnabledIntent,
	preparePrReviewIntent,
	registerPushTargetIntent,
	removeWorktreeIntent,
	setAutoCompactionIntent,
	setAutoRetryIntent,
	setCompactionThresholdIntent,
	setDefaultModelIntent,
	setDefaultThinkingLevelIntent,
	setFollowUpModeIntent,
	setKeepAwakeIntent,
	setSteeringModeIntent,
	setWebSearchKeyIntent,
	unregisterWorkspaceIntent,
	uploadDeviceLogsIntent,
} from "./host.ts";
import {
	reviewAcknowledgeIntent,
	reviewBranchIntent,
	reviewCommitIntent,
	reviewExportFeedbackIntent,
	reviewOpenSessionIntent,
	reviewPrIntent,
	reviewPublishIntent,
	reviewRecordFindingOutcomeIntent,
	reviewRerunIntent,
	reviewResetDiscussionIntent,
	reviewStartDiscussionsIntent,
	reviewUncommittedIntent,
} from "./review.ts";
import type { IntentDefinition } from "./types.ts";
import { cancelWorkIntent, openWorkIntent, resumeWorkIntent, startSubagentIntent } from "./work.ts";

/**
 * Every built-in intent's definition, in protocol order. A function, so the
 * registry reads the definitions when first used, after every definition
 * module finished loading, whatever order a host's imports load them in.
 */
export function createBuiltinIntents() {
	return {
		prompt: promptIntent,
		steer: steerIntent,
		follow_up: followUpIntent,
		abort: abortIntent,
		abort_retry: abortRetryIntent,
		bash: bashIntent,
		abort_bash: abortBashIntent,
		compact: compactIntent,
		set_model: setModelIntent,
		set_thinking_level: setThinkingLevelIntent,
		set_fast_mode: setFastModeIntent,
		set_session_name: setSessionNameIntent,
		set_agent_mode: setAgentModeIntent,
		plan_execute: planExecuteIntent,
		plan_change: planChangeIntent,
		plan_discard: planDiscardIntent,
		new_session: newSessionIntent,
		switch_session: switchSessionIntent,
		fork: forkIntent,
		clone: cloneIntent,
		export_html: exportHtmlIntent,
		cancel_work: cancelWorkIntent,
		open_work: openWorkIntent,
		resume_work: resumeWorkIntent,
		start_subagent: startSubagentIntent,
		review_uncommitted: reviewUncommittedIntent,
		review_branch: reviewBranchIntent,
		review_pr: reviewPrIntent,
		review_commit: reviewCommitIntent,
		review_rerun: reviewRerunIntent,
		review_open_session: reviewOpenSessionIntent,
		review_acknowledge: reviewAcknowledgeIntent,
		review_record_finding_outcome: reviewRecordFindingOutcomeIntent,
		review_publish: reviewPublishIntent,
		review_export_feedback: reviewExportFeedbackIntent,
		review_start_discussions: reviewStartDiscussionsIntent,
		review_reset_discussion: reviewResetDiscussionIntent,
		set_default_model: setDefaultModelIntent,
		set_default_thinking_level: setDefaultThinkingLevelIntent,
		set_steering_mode: setSteeringModeIntent,
		set_follow_up_mode: setFollowUpModeIntent,
		set_auto_retry: setAutoRetryIntent,
		set_auto_compaction: setAutoCompactionIntent,
		set_compaction_threshold: setCompactionThresholdIntent,
		set_keep_awake: setKeepAwakeIntent,
		set_web_search_key: setWebSearchKeyIntent,
		upload_device_logs: uploadDeviceLogsIntent,
		"mcp.connect": mcpConnectIntent,
		"mcp.disconnect": mcpDisconnectIntent,
		"mcp.refresh": mcpRefreshIntent,
		"mcp.set_enabled": mcpSetEnabledIntent,
		"mcp.auth_start_device": mcpAuthStartDeviceIntent,
		"mcp.auth_start_browser": mcpAuthStartBrowserIntent,
		"mcp.auth_complete": mcpAuthCompleteIntent,
		"mcp.auth_poll": mcpAuthPollIntent,
		"mcp.auth_cancel": mcpAuthCancelIntent,
		"mcp.logout": mcpLogoutIntent,
		register_push_target: registerPushTargetIntent,
		unregister_workspace: unregisterWorkspaceIntent,
		create_worktree: createWorktreeIntent,
		remove_worktree: removeWorktreeIntent,
		prepare_pr_review: preparePrReviewIntent,
	} as const satisfies { readonly [N in BuiltinIntentName]: IntentDefinition<N, unknown> };
}
