/**
 * Extension system for lifecycle events and custom tools.
 */

export type { SlashCommandInfo, SlashCommandSource } from "../slash-commands.ts";
export type { SourceInfo } from "../source-info.ts";
export {
	createExtensionRuntime,
	discoverAndLoadExtensions,
	type ExtensionSource,
	loadExtensionFromFactory,
	loadExtensions,
} from "./loader.ts";
export {
	declaresPackageExtension,
	defineManifest,
	type ExtensionManifest,
	ExtensionManifestError,
	LOCAL_EXTENSION_VERSION,
	type PackageExtension,
	readModuleManifest,
	readPackageManifest,
	validateManifest,
} from "./manifest.ts";
export {
	describePermissions,
	EXTENSION_PERMISSION_DESCRIPTIONS,
	ExtensionPermissionError,
	ExtensionPermissionStore,
	extensionFingerprint,
	type PermissionAcknowledgment,
	type PermissionReview,
	type PermissionSubject,
	permissionSubject,
} from "./permissions.ts";
export type {
	DiscoveredResourcePath,
	ExtensionErrorListener,
	ForkHandler,
	NavigateTreeHandler,
	NewSessionHandler,
	ShutdownHandler,
	SwitchSessionHandler,
} from "./runner.ts";
export { ExtensionMessageRoleMismatchError, ExtensionRunner } from "./runner.ts";
export type {
	ExtensionOperationEvent,
	ExtensionOperationOrigin,
	ExtensionServiceName,
	ExtensionServicesCause,
	ExtensionServicesContext,
	ExtensionServicesContribution,
	ExtensionServicesEvidence,
	ExtensionServicesFailure,
	ExtensionServicesFailureStatus,
	ExtensionServicesFindResult,
	ExtensionServicesInput,
	ExtensionServicesLimits,
	ExtensionServicesLocation,
	ExtensionServicesLocationsResult,
	ExtensionServicesReadResult,
	ExtensionServicesRepository,
	ExtensionServicesSearchResult,
	ExtensionServicesSkill,
	ExtensionServicesSnapshot,
	ExtensionServicesStatus,
	ExtensionServicesSymbol,
	ExtensionServicesSymbolsResult,
	ExtensionServicesTaskAdmission,
	ExtensionServicesTaskContext,
	ExtensionServicesTaskHandle,
	ExtensionServicesTaskSpec,
	ExtensionServicesTaskState,
	ExtensionServicesTaskSummary,
	RequestBoundaryEvent,
} from "./services-types.ts";
export {
	ExtensionSettingsError,
	type ExtensionSettingsOf,
	type ExtensionSettingValue,
	settingsFormFields,
} from "./settings.ts";
export type {
	AfterProviderResponseEvent,
	AgentEndEvent,
	AgentStartEvent,
	// Re-exports
	AgentToolResult,
	AgentToolUpdateCallback,
	AppendEntryHandler,
	// App keybindings (for custom editors)
	AppKeybinding,
	AutocompleteProviderFactory,
	// Events - Tool (ToolCallEvent types)
	BashToolCallEvent,
	BashToolResultEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	// Context
	CompactOptions,
	// Events - Agent
	ContextEvent,
	// Event Results
	ContextEventResult,
	ContextUsage,
	CustomToolCallEvent,
	CustomToolResultEvent,
	EditorFactory,
	EditToolCallEvent,
	EditToolResultEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	// API
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionCompletionItem,
	ExtensionCompletionProvider,
	ExtensionCompletionRequest,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionDefinition,
	ExtensionDialog,
	ExtensionDialogAction,
	// Errors
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionForm,
	ExtensionFormValues,
	ExtensionHandler,
	ExtensionIntentOptions,
	ExtensionMode,
	ExtensionPanel,
	ExtensionPanelPlacement,
	// Runtime
	ExtensionRuntime,
	ExtensionSettingsShape,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	FindToolResultEvent,
	GetActiveToolsHandler,
	GetAllToolsHandler,
	GetCommandsHandler,
	GetThinkingLevelHandler,
	GrepToolCallEvent,
	GrepToolResultEvent,
	// Events - Input
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	LsToolResultEvent,
	// Events - Message
	MessageEndEvent,
	// Message Rendering
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ModelSelectEvent,
	ModelSelectSource,
	PolicyRegistration,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	// Provider Registration
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	ReadToolResultEvent,
	// Commands
	RegisteredCommand,
	RegisteredCompletionProvider,
	RegisteredIntent,
	RegisteredTool,
	ReplacedSessionContext,
	ResolvedCommand,
	// Events - Resources
	ResourcesDiscoverEvent,
	ResourcesDiscoverResult,
	SendMessageHandler,
	SendUserMessageHandler,
	SessionBeforeCompactEvent,
	SessionBeforeCompactResult,
	SessionBeforeForkEvent,
	SessionBeforeForkResult,
	SessionBeforeSwitchEvent,
	SessionBeforeSwitchResult,
	SessionBeforeTreeEvent,
	SessionBeforeTreeResult,
	SessionCompactEvent,
	SessionEvent,
	SessionIntentResult,
	SessionShutdownEvent,
	// Events - Session
	SessionStartEvent,
	SessionTreeEvent,
	SetActiveToolsHandler,
	SetLabelHandler,
	SetModelHandler,
	SetThinkingLevelHandler,
	SettingsChangedEvent,
	StartWorkOptions,
	TerminalInputHandler,
	// Events - Tool
	ToolCallEvent,
	ToolCallEventResult,
	// Tools
	ToolDefinition,
	// Events - Tool Execution
	ToolExecutionEndEvent,
	// Tool execution mode
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	ToolResultEventResult,
	TreePreparation,
	TurnEndEvent,
	TurnStartEvent,
	// Events - User Bash
	UserBashEvent,
	UserBashEventResult,
	WebFetchToolCallEvent,
	WebFetchToolResultEvent,
	WebSearchToolCallEvent,
	WebSearchToolResultEvent,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WorkKindDeclaration,
	WorkRun,
	WorkRunContext,
	WorkRunResult,
	WriteToolCallEvent,
	WriteToolResultEvent,
} from "./types.ts";
// Type guards
export {
	defineTool,
	ExtensionUIDismissedError,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWebFetchToolResult,
	isWebSearchToolResult,
	isWriteToolResult,
} from "./types.ts";
export { wrapRegisteredTool, wrapRegisteredTools } from "./wrapper.ts";
